# Generated by Django 5.2.16 on 2026-08-10 19:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('slug', models.SlugField()),
                ('prompt', models.TextField()),
                ('instructions', models.TextField(blank=True)),
                ('answer_type', models.CharField(default='text', max_length=50)),
                ('expected_answer', models.TextField(blank=True)),
                ('hint', models.TextField(blank=True)),
                ('solution', models.TextField(blank=True)),
                ('image_url', models.URLField(blank=True)),
                ('external_link', models.URLField(blank=True)),
                ('book_reference', models.CharField(blank=True, max_length=255)),
                ('order', models.PositiveIntegerField(default=1)),
                ('is_published', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('chapter', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='courses.chapter')),
                ('learning_set', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='courses.learningset')),
            ],
            options={
                'ordering': ['order', 'title'],
                'unique_together': {('learning_set', 'slug')},
            },
        ),
    ]
