# Generated by Django 5.2.16 on 2026-08-12 18:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='answer_type',
            field=models.CharField(choices=[('checkbox', 'Checkbox'), ('input_field', 'Input field'), ('multiple_choice', 'Multiple choice')], default='input_field', max_length=24),
        ),
        migrations.CreateModel(
            name='TaskOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=255)),
                ('is_correct', models.BooleanField(default=False)),
                ('position', models.PositiveIntegerField(default=0)),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='options', to='tasks.task')),
            ],
            options={
                'ordering': ['position', 'id'],
            },
        ),
    ]
