# Generated by Django 5.2.16 on 2026-08-14 20:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_alter_chapter_unique_together_and_more'),
        ('tasks', '0002_alter_task_answer_type_taskoption'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='chapter',
        ),
        migrations.AddField(
            model_name='task',
            name='topic',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='courses.topic'),
        ),
    ]
