# Generated by Django 5.2.16 on 2026-08-15 20:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0003_remove_task_chapter_task_topic'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='disk_reward',
            field=models.PositiveIntegerField(default=100),
        ),
    ]
