# Generated by Django 5.2.16 on 2026-08-24 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0004_task_disk_reward'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='answer_type',
            field=models.CharField(choices=[('checkbox', 'Checkbox'), ('input_field', 'Input field'), ('multiple_choice', 'Multiple choice'), ('equation', 'Equation')], default='input_field', max_length=24),
        ),
    ]
