[mypy]
plugins = mypy_django_plugin.main
python_version = 3.11
mypy_path = diskmatte-the-game
warn_unused_ignores = True
warn_redundant_casts = True
check_untyped_defs = False
exclude = (?x)(^diskmatte-the-game/apps/.*/migrations/.*$)

[mypy.plugins.django-stubs]
django_settings_module = diskmatte.settings.dev
