# Generated by Django 5.2.16 on 2026-08-14 20:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_alter_chapter_unique_together_and_more'),
        ('tasks', '0003_remove_task_chapter_task_topic'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Chapter',
        ),
        migrations.AlterUniqueTogether(
            name='topic',
            unique_together={('course', 'slug')},
        ),
    ]
