# Generated by Django 5.2.16 on 2026-08-16 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('progress', '0002_disktransaction_userwallet'),
    ]

    operations = [
        migrations.AddField(
            model_name='userwallet',
            name='total',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
