# Generated by Django 5.2.16 on 2026-08-16 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cosmetics', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='skin',
            name='kind',
            field=models.CharField(choices=[('color', 'Färg'), ('image', 'Bild'), ('css_class', 'CSS-klass')], default='color', max_length=20),
        ),
    ]
