# Generated by Django 5.2.16 on 2026-08-16 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cosmetics', '0002_skin_kind'),
    ]

    operations = [
        migrations.AddField(
            model_name='skin',
            name='image',
            field=models.CharField(blank=True, help_text='Sökväg relativt static/, t.ex. cosmetics/skins/lava.png', max_length=255),
        ),
        migrations.AlterField(
            model_name='skin',
            name='color',
            field=models.CharField(default='#de2a2a', max_length=7),
        ),
    ]
