# Generated by Django 5.2.16 on 2026-08-20 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cosmetics', '0003_skin_image_alter_skin_color'),
    ]

    operations = [
        migrations.AddField(
            model_name='skin',
            name='css_class',
            field=models.CharField(blank=True, help_text='CSS-klass definierad i skins.css, t.ex. skin-galax', max_length=100),
        ),
    ]
