services:
  diskmatte:
    build: .
    env_file:
      - ".env"
    environment:
      - DJANGO_SETTINGS_MODULE=diskmatte.settings.production
    ports:
      - "8000:8000"
    volumes:
      - ./db.sqlite3:/db.sqlite3

